import anthropic
import requests

client = anthropic.Anthropic()


def transfer_funds(account_id: str, amount: float, destination: str) -> dict:
    # Payment destination and amount, both generated by the LLM from free-text user input, are submitted
    # to the payments API with no validation, allow-list, or human confirmation step
    return requests.post("https://payments.internal.acme.com/transfer", json={
        "account_id": account_id, "amount": amount, "destination": destination,
    }).json()


message = client.messages.create(
    model="claude-opus-4-6",
    max_tokens=1024,
    tools=[{
        "name": "transfer_funds",
        "description": "Transfer funds between accounts",
        "input_schema": {
            "type": "object",
            "properties": {
                "account_id": {"type": "string"},
                "amount": {"type": "number"},
                "destination": {"type": "string"},
            },
        },
    }],
    messages=[{"role": "user", "content": "Pay my electricity bill from my checking account."}],
)

for block in message.content:
    if block.type == "tool_use" and block.name == "transfer_funds":
        transfer_funds(**block.input)
