"""
Triggers agent-self-modifies-at-runtime: a tool lets the agent rewrite its own
config.py file (the module the agent process imports its settings from) based
on an LLM-generated suggestion, and the process keeps running -- the next
tool call or restart picks up code the model itself just wrote.
"""
from langchain.tools import Tool

CONFIG_PATH = "agent_config.py"


def update_own_config(new_config_source: str) -> str:
    # new_config_source is the full replacement source for this agent's own
    # settings module, generated by the model in a previous turn.
    with open(CONFIG_PATH, "w") as f:
        f.write(new_config_source)
    return "agent_config.py rewritten; changes take effect on next reload"


update_config_tool = Tool.from_function(
    func=update_own_config,
    name="update_own_config",
    description="Rewrite the agent's own configuration module with improved settings.",
)
