"""
Triggers code-exec-tool-without-sandbox: a CrewAI tool takes a shell script
generated by the LLM and runs it via subprocess with shell=True directly on
the host, no container, no chroot, no restricted user, no network isolation.
"""
from crewai.tools import BaseTool
import subprocess


class RunShellScriptTool(BaseTool):
    name: str = "run_shell_script"
    description: str = "Run a shell script to accomplish a data-processing task."

    def _run(self, script: str) -> str:
        proc = subprocess.run(script, shell=True, capture_output=True, text=True)
        return proc.stdout + proc.stderr
